/** Navigation des 24 modules de spécialités (modules 03-26, ports 8100-8123). */
export const MODULE_NAV: Array<{ to: string; label: string }> = [
  { to: "/module/oncology", label: "🎗️ Oncologie" },
  { to: "/module/tumor", label: "🧠 Tumeurs" },
  { to: "/module/ophthalmology", label: "👁️ Ophtalmologie" },
  { to: "/module/diabetes", label: "🩸 Diabétologie" },
  { to: "/module/traumatology", label: "🦴 Traumatologie" },
  { to: "/module/cardiology", label: "❤️ Cardiologie" },
  { to: "/module/pneumology", label: "🫁 Pneumologie" },
  { to: "/module/obstetrics", label: "🤰 Obstétrique" },
  { to: "/module/gynecology", label: "🌸 Gynécologie" },
  { to: "/module/fertility", label: "🧬 Fertilité" },
  { to: "/module/neurology", label: "🧠 Neurologie" },
  { to: "/module/psychiatry", label: "🧬 Psychiatrie" },
  { to: "/module/pediatrics", label: "👶 Pédiatrie" },
  { to: "/module/nephrology", label: "🫘 Néphrologie" },
  { to: "/module/gastroenterology", label: "🫄 Gastro-entéro" },
  { to: "/module/dermatology", label: "🩹 Dermatologie" },
  { to: "/module/ent", label: "👂 ORL" },
  { to: "/module/rheumatology", label: "🦴 Rhumatologie" },
  { to: "/module/urology", label: "🚹 Urologie" },
  { to: "/module/nuclear-medicine", label: "☢️ Médecine nucléaire" },
  { to: "/module/radiotherapy", label: "🎯 Radiothérapie" },
  { to: "/module/anesthesia", label: "💉 Anesthésie" },
  { to: "/module/geriatrics", label: "👴 Gériatrie" },
  { to: "/module/emergency", label: "🚨 Urgences" },
];
